version: '3.5'

services:
        nethermind-lh:
                image: nethermind/nethermind:1.14.2
                container_name: nethermind-lh
                restart: unless-stopped
                ports:
                        - 8545:8545
                        - 30303:30303
                network_mode: host
                command: >-
                        --config=${NETWORK}
                        --JsonRpc.Host=0.0.0.0
                        --JsonRpc.Port=8545
                        --JsonRpc.EnginePort=8551
                        --JsonRpc.AdditionalRpcUrls=http://localhost:8551|http;wss|engine;eth;net;subscribe
                        --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret
                        --Network.P2PPort=30303
                        --Network.DiscoveryPort=30303
                        --HealthChecks.Enabled=true 
                        --HealthChecks.UIEnabled=true


                volumes:
                        - ${LH_DATA_FOLDER}/.nethermind-lh/nethermind_db:/nethermind/nethermind_db
                        - ${LH_DATA_FOLDER}/.nethermind-lh/logs:/nethermind/logs
                        - ${LH_DATA_FOLDER}/.nethermind-lh/keystore:/nethermind/keystore
                        - ./data:/tmp/ethereum
        
        lighthouse:
                image: sigp/lighthouse:v3.1.2
                container_name: lighthouse
                restart: unless-stopped
                ports:
                        - 9001:9001
                        - 5052:5052
                network_mode: host
                command: >-
                        lighthouse
                        --spec=mainnet
                        --network=${NETWORK}
                        --debug-level=info
                        --logfile-debug-level=info
                        --logfile=/root/.lighthouse/lighthouse.log
                        beacon_node
                        --eth1
                        --http
                        --http-allow-sync-stalled
                        --metrics
                        --execution-endpoints=http://127.0.0.1:8551
                        --enr-udp-port=9001
                        --enr-tcp-port=9001
                        --discovery-port=9001
                        --jwt-secrets=/tmp/ethereum/jwtsecret
                        --suggested-fee-recipient=${FEE_RECIPIENT}

                volumes:
                        - ${LH_DATA_FOLDER}/.lighthouse:/root/.lighthouse
                        - ./data:/tmp/ethereum
                depends_on:
                        - nethermind-lh

        nethermind-prysm:
                image: nethermind/nethermind:1.14.2
                container_name: nethermind-prysm
                restart: unless-stopped
                ports:
                        - 8546:8546
                        - 30304:30304
                network_mode: host
                command: >-
                        --config=${NETWORK}
                        --JsonRpc.Host=0.0.0.0
                        --JsonRpc.Port=8546
                        --JsonRpc.EnginePort=8552
                        --JsonRpc.AdditionalRpcUrls=http://localhost:8552|http;wss|engine;eth;net;subscribe
                        --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret
                        --Network.P2PPort=30304
                        --Network.DiscoveryPort=30304
                        --HealthChecks.Enabled=true 
                        --HealthChecks.UIEnabled=true


                volumes:
                        - ${PRYSM_DATA_FOLDER}/.nethermind-prysm/nethermind_db:/nethermind/nethermind_db
                        - ${PRYSM_DATA_FOLDER}/.nethermind-prysm/logs:/nethermind/logs
                        - ${PRYSM_DATA_FOLDER}/.nethermind-prysm/keystore:/nethermind/keystore
                        - ./data:/tmp/ethereum
        prysm:
                image: gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.1
                container_name: prysm
                restart: unless-stopped
                ports:
                        - 9000:9000
                        - 3500:3500
                network_mode: host
                command: >-
                        --accept-terms-of-use
                        --${NETWORK}
                        --suggested-fee-recipient=${FEE_RECIPIENT}
                        --http-web3provider=http://localhost:8552
                        --jwt-secret=/tmp/ethereum/jwtsecret
                        --log-file=/home/.eth2/prysm.log
                volumes:
                        - ${PRYSM_DATA_FOLDER}/.prysm:/home/.eth2/
                        - ./data:/tmp/ethereum
                depends_on:
                        - "nethermind-prysm"
        nethermind-teku:
                image: nethermind/nethermind:1.14.2
                container_name: nethermind-teku
                restart: unless-stopped
                ports:
                        - 8547:8547
                        - 30305:30305
                network_mode: host
                command: >-
                        --config=${NETWORK}
                        --JsonRpc.Host=0.0.0.0
                        --JsonRpc.Port=8547
                        --JsonRpc.EnginePort=8553
                        --JsonRpc.AdditionalRpcUrls=http://localhost:8553|http;wss|engine;eth;net;subscribe
                        --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret
                        --Network.P2PPort=30305
                        --Network.DiscoveryPort=30305
                        --HealthChecks.Enabled=true 
                        --HealthChecks.UIEnabled=true


                volumes:
                        - ${TEKU_DATA_FOLDER}/.nethermind-teku/nethermind_db:/nethermind/nethermind_db
                        - ${TEKU_DATA_FOLDER}/.nethermind-teku/logs:/nethermind/logs
                        - ${TEKU_DATA_FOLDER}/.nethermind-teku/keystore:/nethermind/keystore
                        - ./data:/tmp/ethereum
        teku:
                image: consensys/teku:22.9.1
                container_name: teku
                restart: unless-stopped
                ports:
                        - 9002:9002
                        - 5051:5051
                network_mode: host
                command: >-
                        --network=${NETWORK}
                        --p2p-port=9002
                        --ee-endpoint=http://localhost:8553
                        --ee-jwt-secret-file=/tmp/ethereum/jwtsecret
                        --log-destination=FILE
                        --validators-proposer-default-fee-recipient=${FEE_RECIPIENT}
                        --log-file=/opt/teku/.local/share/teku/teku.log
                        --metrics-enabled=true
                        --rest-api-enabled=true
                
                volumes:
                        - ${TEKU_DATA_FOLDER}/.teku:/opt/teku/.local/share/teku/
                        - ./data:/tmp/ethereum
                # Check teku host directory permissions as it throws an error(777)
                depends_on:
                        - "nethermind-teku"
        nethermind-nimbus:
                image: nethermind/nethermind:1.14.2
                container_name: nethermind-nimbus
                restart: unless-stopped
                ports:
                        - 8548:8548
                        - 30306:30306
                network_mode: host
                command: >-
                        --config=${NETWORK}
                        --JsonRpc.Host=0.0.0.0
                        --JsonRpc.Port=8548
                        --JsonRpc.EnginePort=8554
                        --JsonRpc.AdditionalRpcUrls=http://localhost:8554|http;wss|engine;eth;net;subscribe
                        --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret
                        --Network.P2PPort=30306
                        --Network.DiscoveryPort=30306
                        --HealthChecks.Enabled=true 
                        --HealthChecks.UIEnabled=true


                volumes:
                        - ${NIMBUS_DATA_FOLDER}/.nethermind-nimbus/nethermind_db:/nethermind/nethermind_db
                        - ${NIMBUS_DATA_FOLDER}/.nethermind-nimbus/logs:/nethermind/logs
                        - ${NIMBUS_DATA_FOLDER}/.nethermind-nimbus/keystore:/nethermind/keystore
                        - ./data:/tmp/ethereum
        nimbus-sproul:
                image: nimbus-sproul:latest
                build:
                        context: ./.nimbus/
                        dockerfile: Dockerfile
                container_name: nimbus-sproul
                restart: unless-stopped
                ports:
                        - 9003:9003
                        - 5053:5053
                network_mode: host
                command: >-
                        --network=${NETWORK}
                        --web3-url=http://127.0.0.1:8554
                        --rest
                        --metrics
                        --jwt-secret=/tmp/ethereum/jwtsecret
                        --suggested-fee-recipient=${FEE_RECIPIENT}
                        --tcp-port=9003
                        --udp-port=9003
                        --rest-port=5053
                        --metrics-port=8009
                        --log-file=/app/build/data/shared_mainnet_0/nimbus.log


                volumes:
                        - ${NIMBUS_DATA_FOLDER}/.nimbus-sproul:/app/build/data/shared_mainnet_0/
                        - ./data:/tmp/ethereum
                # Check nimbus directory permissions (777)
                depends_on:
                        - nethermind-nimbus
        nimbus:
                image: statusim/nimbus-eth2:amd64-v22.9.1
                container_name: nimbus
                restart: unless-stopped
                ports:
                        - 9003:9003
                        - 5053:5053
                network_mode: host
                command: >-
                        --network=${NETWORK}
                        --web3-url=http://127.0.0.1:8554
                        --rest
                        --metrics
                        --jwt-secret=/tmp/ethereum/jwtsecret
                        --suggested-fee-recipient=${FEE_RECIPIENT}
                        --tcp-port=9003
                        --udp-port=9003
                        --rest-port=5053
                        --metrics-port=8009
                        --log-file=/home/user/.cache/nimbus/nimbus.log


                volumes:
                        - ${NIMBUS_DATA_FOLDER}/.nimbus:/home/user/.cache/nimbus
                        - ./data:/tmp/ethereum
                depends_on:
                        - nethermind-nimbus
                # Check nimbus directory permissions (777)

        nethermind-lodestar:
                image: nethermind/nethermind:1.14.2
                container_name: nethermind-lodestar
                restart: unless-stopped
                ports:
                        - 8549:8549
                        - 30307:30307
                network_mode: host
                command: >-
                        --config=${NETWORK}
                        --JsonRpc.Host=0.0.0.0
                        --JsonRpc.Port=8549
                        --JsonRpc.EnginePort=8555
                        --JsonRpc.AdditionalRpcUrls=http://localhost:8555|http;wss|engine;eth;net;subscribe
                        --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret
                        --Network.P2PPort=30307
                        --Network.DiscoveryPort=30307
                        --HealthChecks.Enabled=true 
                        --HealthChecks.UIEnabled=true


                volumes:
                        - ${LODESTAR_DATA_FOLDER}/.nethermind-lodestar/nethermind_db:/nethermind/nethermind_db
                        - ${LODESTAR_DATA_FOLDER}/.nethermind-lodestar/logs:/nethermind/logs
                        - ${LODESTAR_DATA_FOLDER}/.nethermind-lodestar/keystore:/nethermind/keystore
                        - ./data:/tmp/ethereum
        lodestar:
                image: chainsafe/lodestar:v1.2.1
                container_name: lodestar
                restart: unless-stopped
                ports:
                        - 9004:9004
                        - 9596:9596
                network_mode: host
                command: >-
                        beacon
                        --network=${NETWORK}
                        --port=9004
                        --execution.urls="http://127.0.0.1:8555"
                        --network.connectToDiscv5Bootnodes
                        --suggestedFeeRecipient=${FEE_RECIPIENT}
                        --jwt-secret="/tmp/ethereum/jwtsecret"
                        --logFile=/root/.local/share/lodestar/lodestar.log
                        --metrics=true
                        --metrics.port=8010

                volumes:
                        - ${LODESTAR_DATA_FOLDER}/.lodestar:/root/.local/share/lodestar
                        - ./data:/tmp/ethereum
                depends_on:
                        - "nethermind-lodestar"
        
        prometheus:
                image: prom/prometheus:v2.36.2
                container_name: prometheus
                volumes:
                        - ./prometheus/:/etc/prometheus/
                        - ./apps-data/prometheus:/var/lib/prometheus
                command:
                        - '--config.file=/etc/prometheus/prometheus.yml'
                        - '--storage.tsdb.path=/prometheus'
                        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
                        - '--web.console.templates=/usr/share/prometheus/consoles'
                        - '--web.listen-address=0.0.0.0:9090'
                network_mode: 'host'
                restart: always
        
        node_exporter:
                image: quay.io/prometheus/node-exporter:latest
                container_name: node_exporter
                command:
                  - '--path.rootfs=/host'
                network_mode: host
                pid: host
                restart: unless-stopped
                volumes:
                  - ./apps-data/prometheus-node-exporter:/host:ro,rslave

        grafana:
                build: './grafana'
                container_name: 'grafana'
                network_mode: 'host'
                # volumes:
                #   - ./apps-data/grafana:/var/lib/grafana
        
        db:
                image: postgres:14.1-alpine
                restart: always
                environment:
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                volumes: 
                        - ./data/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
                        - ./apps-data/.postgres-data/:/var/lib/postgresql
                network_mode: 'host'

        
        vouch:
                image: vouch-tdahar:latest
                build:
                        context: ./.vouch/
                        dockerfile: Dockerfile
                container_name: vouch

                network_mode: 'host'
                restart: always
                volumes: 
                        - ./apps-data/.vouch/data:/app/logs

                

        
        