# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      server: 'server_ip'
      project_name: 'project_name'

remote_write:
  - url: http://remote_ip:remote_port/api/v1/write

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # - job_name: 'prysm'
  #   static_configs:
  #     - targets: ['localhost:8080']
  
  # - job_name: 'prysm-val'
  #   static_configs:
  #     - targets: ['localhost:8081']

  # - job_name: 'lighthouse'
  #   static_configs:
  #     - targets: ['localhost:5054']

  # - job_name: 'lighthouse-val'
  #   static_configs:
  #     - targets: ['localhost:5064']

  # - job_name: 'teku'
  #   static_configs:
  #     - targets: ['localhost:8008']

  # - job_name: 'teku-val'
  #   static_configs:
  #     - targets: ['localhost:5065']

  # - job_name: 'nimbus'
  #   static_configs:
  #     - targets: ['localhost:8009']

  # - job_name: 'lodestar'
  #   static_configs:
  #     - targets: ['localhost:8010']

  # - job_name: 'lodestar-val'
  #   static_configs:
  #     - targets: ['localhost:5067']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8090']

  - job_name: 'caddy'
    static_configs:
      - targets: ['localhost:2019']
  
  - job_name: node-exporter
    static_configs:
      - targets: ['localhost:9100']